import type { Metadata } from "next";
import Link from "next/link";
import { ArtworkVisual } from "../components/artwork-visual";
import { PageShell, SectionIntro } from "../components/site-chrome";
import { artworks } from "../data/exhibition";
export const metadata:Metadata={title:"Artists",description:"Artists who pictured Judith, and how the subject entered their careers."};
const biographies:Record<string,string>={
  "artemisia-gentileschi":"A Roman-born painter who worked in Florence, Rome, Venice, Naples, and London, Gentileschi combined Caravaggesque light with formidable narrative construction. In Florence she worked within the Medici court’s orbit and in 1616 became the first woman admitted to the Accademia del Disegno. The Uffizi connects its large Judith to Grand Duke Cosimo II de’ Medici and records both resistance to displaying it and delayed payment secured with Galileo Galilei’s help—evidence that patronage, reputation, money, and access belong beside form and biography. Judith recurs across Gentileschi’s career in the killing, escape, and aftermath; no single event or interpretive key explains that sustained work.",
  "caravaggio":"Caravaggio reorganized history painting around ordinary bodies under coercive light. His Judith belongs to a Roman period of closely staged sacred violence; it converts a familiar aftermath subject into the unstable present tense of a blade meeting flesh.",
  "donatello":"The leading sculptor of early Renaissance Florence made the bronze group late in his career. It was recorded in the Medici garden by 1464, although its original patron and destination remain debated. Confiscated after Piero di Lorenzo de’ Medici’s expulsion, it entered Piazza della Signoria in 1495, moved to the Loggia dei Lanzi in 1506 and the Palazzo Vecchio platform in 1919, and has been conserved in the Sala dei Gigli since 1988. Each move changed who could claim its warning against tyranny and pride.",
  "lucas-cranach":"Court painter to the electors of Saxony, Cranach led a highly productive workshop. His several Judiths combine fashionable dress, polished portrait convention, and a gruesome attribute in a formula whose repeatability was part of its courtly success.",
  "gustav-klimt":"A founder of the Vienna Secession, Klimt used ornament, gold, shallow space, and the female figure to unsettle distinctions between portrait, allegory, and erotic image. Judith I stands at the threshold of his celebrated Golden Period.",
  "francisco-goya":"Goya's long career moved through tapestry designs, court portraiture, war, printmaking, and private experiment. His Judith was painted on the wall of the Quinta del Sordo among the works later called the Black Paintings, never intended as a public cycle.",
  "sandro-botticelli":"Botticelli's early pair of small Judith panels joins lyrical line to Florentine interest in the heroine as civic virtue. Choosing the return and the discovery lets the paintings divide triumph from horror while keeping them materially paired.",
  "rembrandt":"Rembrandt's 1634 painting demonstrates the instability of subject identification. Once called Artemisia or Sophonisba, it is now read by the Prado as Judith at Holofernes's banquet—a title that makes suspended luxury part of the plot.",
  "trophime-bigot":"Bigot is associated with candlelit scenes made during a career reconstructed from fragmentary evidence. The Walters attributes this painting to him and dates it about 1640; both the boundaries of his oeuvre and older links to the so-called Candlelight Master remain subjects of scholarly debate.",
};
export default function ArtistsPage(){const groups=Object.entries(artworks.reduce((a,w)=>{(a[w.artistSlug]||=[]).push(w);return a},{} as Record<string,typeof artworks>));return <PageShell className="artists-page"><SectionIntro eyebrow={`${groups.length} artistic positions`} title="Artists"><p>Judith enters careers at different scales: a repeated workshop type, a civic monument, a private wall painting, an engraved translation, or a subject revised over decades.</p></SectionIntro><nav className="artist-index" aria-label="Artist index">{groups.map(([slug,works])=><a href={`#${slug}`} key={slug}>{works[0].artist}</a>)}</nav><section className="artist-profiles">{groups.map(([slug,works])=><article id={slug} key={slug}><div className="artist-heading"><p className="eyebrow">{works[0].artistDates} · {works[0].region}</p><h2>{works[0].artist}</h2><p>{biographies[slug]||`${works[0].artist} enters this exhibition through ${works.length>1?`${works.length} works that make repetition and variation visible`:`a work that locates Judith within ${works[0].movement.toLowerCase()}`}. The object record distinguishes established catalog data from the curatorial connections drawn here.`}</p></div><div className="artist-works">{works.map(w=><Link href={`/artworks/${w.slug}`} key={w.slug}><ArtworkVisual work={w}/><span>{w.dateDisplay}<b>{w.title}</b></span></Link>)}</div><div className="artist-context"><p className="eyebrow">Judith in the career</p><p>{works.length>1?`These works make change visible across versions: pose, helper, light, force, and the selected narrative instant become evidence of continued artistic thought rather than mere duplication.`:`Here Judith concentrates concerns already active in the artist's practice: ${works[0].themes.slice(0,3).join(", ").toLowerCase()}.`}</p></div></article>)}</section></PageShell>}
