import type { Metadata } from "next";
import Link from "next/link";
import { ArtworkVisual } from "../components/artwork-visual";
import { PageShell, SectionIntro } from "../components/site-chrome";
import { artworkImage, artworks, interpretationEras } from "../data/exhibition";

export const metadata: Metadata = { title: "Judith Through Time", description: "A visual history of Judith from biblical heroine and civic liberator to femme fatale and feminist icon." };
const eraWorks = ["cleveland-bible-initial","cleveland-bible-initial","donatello-judith","cranach-met-judith","artemisia-florence","klimt-judith-i","kehinde-wiley-judith"];
export default function InterpretationPage() { return <PageShell className="essay-page interpretation-page"><SectionIntro eyebrow="A visual argument" title="Judith Through Time"><p>The same narrative has served devotion, civic liberty, court display, political satire, erotic fantasy, feminist revision, and critiques of race and museum power. The shifts are historical claims to test against objects, not proof of a single evolutionary path.</p></SectionIntro>
  <section className="interpretation-thesis"><p>Not a march from faith to sex. Not a neat replacement of heroine by monster. Meanings accumulate, retreat, and return.</p></section>
  <section className="era-timeline">{interpretationEras.map(([date,title,text],i) => { const work = artworks.find(w => w.slug === eraWorks[i])!; return <article key={title}><div className="era-date">{date}</div><Link href={`/artworks/${work.slug}`} className="era-image"><ArtworkVisual work={work} /></Link><div className="era-copy"><p className="eyebrow">Movement {String(i+1).padStart(2,"0")}</p><h2>{title}</h2><p>{text}</p><Link className="text-link" href={`/gallery?view=chronology`}>See the chronology <span>→</span></Link></div></article>; })}</section>
  <section className="literary-bridge section-pad"><p className="eyebrow">Words around the images</p><h2>The visual tradition did not travel alone.</h2><div><p>The incomplete Old English <i>Judith</i>, preserved in the Nowell Codex after <i>Beowulf</i>, turns the heroine into vernacular heroic poetry. Friedrich Hebbel's 1840 tragedy later transforms the political story into a psychological and sexual conflict that matters to nineteenth-century reception.</p><p>Neither text supplies a master key for every artwork. Together they show why a visual timeline that jumps directly from scripture to painting misses part of the machinery by which Judith changed. <a href="https://www.openbookpublishers.com/books/10.11647/obp.0009" target="_blank" rel="noreferrer">Read the interdisciplinary scholarship in <i>The Sword of Judith</i> ↗</a></p></div></section>
  <section className="medium-argument section-pad"><div><p className="eyebrow">Media change the argument</p><h2>A print is not merely a smaller painting.</h2></div><div><p><Link href="/artworks/mocetto-judith">Mocetto&apos;s engraving after Mantegna</Link> made a portable matrix of gestures that could circulate beyond any one court or collection. <Link href="/artworks/bosse-judith">Abraham Bosse&apos;s etching</Link> later moved the violent instant through another reproducible medium. Prints create networks of copying, reversal, reuse, and recognition; those networks are part of the subject&apos;s history.</p><p>Counter-Reformation painting likewise cannot be reduced to a neutral continuation of Renaissance iconography. Judith could operate as Catholic orthodoxy, female exemplarity, devotional drama, and spectacular violence at once. <a href="https://www.openbookpublishers.com/books/10.11647/obp.0009/chapters/10.11647/obp.0009.19" target="_blank" rel="noreferrer">Elena Ciletti&apos;s focused study provides the larger Counter-Reformation frame ↗</a></p></div></section>
  <section className="salome-problem section-pad"><div><p className="eyebrow">An iconographic collision</p><h2>Judith is not Salome.</h2><p>Both can appear as beautiful women with a severed male head and an attendant. Yet the narrative roles oppose one another. Judith plans and performs a tyrant's death to save her city; Salome receives John the Baptist's head after her dance, at another person's instigation.</p><p>As artists suppress swords, sacks, settings, or attendants, the two images can approach each other. Fin-de-siècle culture exploited the ambiguity. In <Link href="/artworks/klimt-judith-i">Klimt&apos;s <i>Judith I</i></Link>, the metal frame itself insists on <i>JUDITH UND HOLOFERNES</i> even as critics repeatedly called the figure Salome. Careful attribution requires objects and sources—not simply recognizing “woman plus head.”</p></div><div className="salome-diagram"><span>Judith</span><i>Sword<br />Bag<br />Bethulia</i><b>Beauty<br />Head<br />Attendant</b><i>Platter<br />Dance<br />Herod</i><span>Salome</span></div></section>
  <section className="interpretation-end"><img src={artworkImage("artemisia-naples")} alt="Detail from Artemisia Gentileschi's Naples Judith." /><div><p className="eyebrow">Modern reception</p><h2>Artemisia is not an illustration of her biography.</h2><p>Mary Garrard’s feminist reading made the heroine and the painter newly visible. Griselda Pollock contests the rape-as-master-key from within feminist and psychoanalytic reading practice: what matters includes how art history teaches us to read gendered images. R. Ward Bissell approaches Artemisia through documentary connoisseurship, chronology, attribution, and patronage, an approach often criticized for underweighting gender. These are not one correction but a three-cornered argument.</p><p>The rape and 1612 trial belong to that reception history, but no single biographical or anti-biographical formula explains the paintings.</p><div className="interpretation-actions"><Link className="button button--primary" href="/artists#artemisia-gentileschi">Meet the artist →</Link><Link className="button button--outline" href="/sources#artemisia-scholarship">See the debate's sources →</Link></div></div></section>
  </PageShell>; }
