import type { Metadata } from "next";
import Link from "next/link";
import { PageShell, SectionIntro } from "../components/site-chrome";
import { artworkImage } from "../data/exhibition";

export const metadata: Metadata = { title: "Why Judith?", description: "Why artists returned to Judith and Holofernes for centuries: politics, gender, drama, beauty, violence, and symbolic instability." };
const argumentsList = [
  ["01","A perfect dramatic machine","The story supplies disguise, entrance, banquet, drunkenness, isolation, a borrowed sword, two blows, concealment, escape, discovery, rout, and triumph. An artist can choose suspense, impact, or consequence without leaving the same compact narrative."],
  ["02","The weak defeat the strong","Judith enters with one maid, no army, and no official command. Holofernes commands imperial force. That disproportion makes the reversal useful wherever viewers need an image of city against tyrant, faith against empire, or intelligence against mass."],
  ["03","Beauty does political work","The text makes Judith's beauty instrumental but does not make her sexually available to Holofernes. Artists inherit a productive discomfort: seduction without consummation, virtue acting through appearance, a male gaze that becomes the general's tactical failure."],
  ["04","The head changes the picture","A severed head is victim, trophy, proof, burden, still life, portrait, and warning. Hide it in a bag and the image concerns complicity and escape. Lift it by the hair and the scene becomes display. Crop it, as Klimt does, and denial becomes part of looking."],
  ["05","A heroine acts decisively","Judith does not wait to be rescued. That agency can be praised as courage, contained as chastity, politicized as liberty, eroticized as threat, or recovered as feminist force. Each reading says something about the viewer's expectations of women and power."],
  ["06","The story tolerates contradiction","Judith prays and deceives. She dresses magnificently after austere widowhood. She saves by killing, returns to private life after public triumph, and refuses the marriages that might domesticate her victory. She never becomes symbolically safe."],
];
export default function WhyJudithPage() { return <PageShell className="essay-page why-page"><SectionIntro eyebrow="The exhibition's central question" title="Why Judith?"><p>David also cuts off a giant's head. Jael also kills an enemy commander. Salome also stands near a head. Judith's particular combination of civic rescue, beauty used as strategy, prayer, deception, two-handed violence, and public proof gave artists unusually many moments and arguments to choose from.</p></SectionIntro>
  <section className="why-hero"><img src={artworkImage("allori-judith")} alt="Cristofano Allori's Judith displays Holofernes's head." /><blockquote>Artists kept returning because Judith could mean almost anything—<em>except nothing.</em></blockquote></section>
  <section className="argument-list">{argumentsList.map(([n,title,text],i) => <article key={n}><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div>{i === 1 && <img src={artworkImage("donatello-judith")} alt="Donatello's civic bronze Judith and Holofernes." />}{i === 3 && <img src={artworkImage("cranach-met-judith")} alt="Cranach's Judith holding the head." />}</article>)}</section>
  <section className="david-judith section-pad"><p className="eyebrow">The nearest biblical parallel</p><h2>Judith and David</h2><div><p>Both deliver Israel when conventional military strength fails. Both approach a superior enemy and remove his head with his own weapon. Renaissance Florence placed Donatello's two heroes into an especially charged dialogue.</p><p>But gender changes everything. David's beautiful youth can heighten divine election without turning victory into seduction. Judith's beauty becomes part of strategy, and later viewers repeatedly make it answer for anxieties the text assigns to Holofernes.</p></div></section>
  <section className="why-conclusion"><p className="eyebrow">No final label</p><h2>The conditions change; the argument changes with them.</h2><p>A bronze in a republican square, a private mural, a courtly panel, a photograph, and a museum-scale portrait do different political work. The exhibition treats those differences as evidence instead of compressing them into one universal Judith.</p><div><Link className="button button--primary" href="/gallery">Test the argument in the gallery</Link><Link className="button button--outline" href="/compare">Compare two Judiths</Link></div></section>
  </PageShell>; }
