import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArtworkVisual } from "../../components/artwork-visual";
import { Footer, Header } from "../../components/site-chrome";
import { artworks, artworkImage, commonsPage, getArtwork } from "../../data/exhibition";

export const generateStaticParams = () => artworks.map(({ slug }) => ({ slug }));
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const work = getArtwork((await params).slug); return work ? { title: `${work.title} — ${work.artist}`, description: work.shortLabel } : { title: "Artwork not found" }; }

export default async function ArtworkPage({ params }: { params: Promise<{ slug: string }> }) {
  const work = getArtwork((await params).slug); if (!work) notFound();
  const sameScene = artworks.filter(w => w.slug !== work.slug && w.scene === work.scene).slice(0,3); const contrasts = artworks.filter(w => w.slug !== work.slug && w.scene !== work.scene).sort((a,b) => Math.abs(a.dateStart-work.dateStart)-Math.abs(b.dateStart-work.dateStart)).slice(0,2); const related = [...sameScene,...contrasts].slice(0,4);
  const ordered = [...artworks].sort((a,b) => a.dateStart - b.dateStart); const index = ordered.findIndex(w => w.slug === work.slug); const previous = ordered[(index - 1 + ordered.length) % ordered.length]; const next = ordered[(index + 1) % ordered.length];
  const imageSource = work.imageSource || (work.imageFile ? commonsPage(work.imageFile) : work.primarySource);
  const recordSources = [{ label: work.sourceKind || `${work.collection} record`, url: work.primarySource }, ...(work.researchSources || [])]
    .filter((source, sourceIndex, sources) => sources.findIndex(candidate => candidate.url === source.url) === sourceIndex);
  return <><Header /><main id="main" className="object-page">
    <nav className="object-breadcrumb" aria-label="Breadcrumb"><Link href="/gallery">Gallery</Link><span>→</span><span>{work.artist}</span></nav>
    <section className="object-hero"><div className={`object-image-stage ${work.imageFile ? "" : "object-image-stage--text"}`}><ArtworkVisual work={work} loading="eager" />{work.imageFile ? <details className="lights-out"><summary>Full-screen viewing</summary><div><img src={artworkImage(work.slug)} alt={work.alt} /><p>{work.artist}, <i>{work.title}</i>, {work.dateDisplay}</p></div></details> : <div className="object-image-appeal"><p>{work.imageUnavailable}</p><a href={work.primarySource} target="_blank" rel="noreferrer">Open the cited record ↗</a></div>}</div>
      <div className="object-title"><p className="eyebrow">{work.movement} · {work.scene}</p><h1>{work.title}</h1><p className="object-artist"><Link href={`/artists#${work.artistSlug}`}>{work.artist}</Link> <span>{work.artistDates}</span></p><p className="object-date">{work.dateDisplay}</p><div className="object-actions"><Link className="button button--primary" href={`/compare?a=${work.slug}`}>Compare this work</Link>{work.imageFile ? <a className="button button--outline" href={artworkImage(work.slug)} target="_blank">Open image</a> : <a className="button button--outline" href={work.primarySource} target="_blank" rel="noreferrer">Follow the object link</a>}</div></div>
    </section>

    <section className="object-core section-pad"><aside className="object-record"><p className="eyebrow">Object record</p><dl><div><dt>Artist / attribution</dt><dd>{work.artist}</dd></div><div><dt>Date</dt><dd>{work.dateDisplay}</dd></div><div><dt>Medium</dt><dd>{work.medium}</dd></div><div><dt>Dimensions</dt><dd>{work.dimensions}</dd></div><div><dt>Collection</dt><dd>{work.collection}</dd></div><div><dt>Location</dt><dd>{work.location}</dd></div><div><dt>Accession</dt><dd>{work.accession}</dd></div><div><dt>Passage</dt><dd><Link href={`/read?chapter=${work.chapter.replace(/\D/g,"") || 13}`}>{work.chapter}:{work.verses}</Link></dd></div></dl>{work.recordNote && <div className="object-record-note"><p className="eyebrow">Research note</p><p>{work.recordNote}</p></div>}<div className="object-palette" aria-label="Dominant colors">{work.palette.map(color => <span key={color} style={{ background: color }} title={color} />)}</div></aside>
      <article className="object-essay">{work.specialNote && <div className="origin-note"><p className="eyebrow">Where this exhibition began</p><p>{work.specialNote}</p></div>}<div className="wall-label"><p className="eyebrow">Gallery label</p><p>{work.shortLabel}</p></div><h2>Look closely</h2><p>{work.visualAnalysis}</p><h2>Why this Judith matters</h2><p>{work.whyMatters}</p><p className="essay-citations"><span>Sources for this record:</span>{recordSources.map(source => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.label} ↗</a>)}</p><blockquote>“{work.shortLabel}”</blockquote><h2>Narrative index</h2><p>Primary catalogue placement: <b>{work.scene.toLowerCase()}</b>, {work.chapter}:{work.verses}. The index organizes comparison; it does not claim that every visual detail comes from those verses or that the work touches only one episode.</p><div className="theme-list">{work.themes.map(theme => <Link key={theme} href={`/gallery?q=${encodeURIComponent(theme)}`}>{theme}</Link>)}</div></article>
    </section>

    <section className="evidence-strip section-pad"><div><p className="eyebrow">Text and evidence</p><h2>The passage behind the image</h2><p>See the verses in parallel public-domain translations, then return to ask what the artist has omitted, moved, or invented.</p><Link className="text-link" href={`/read?chapter=${work.chapter.replace(/\D/g,"") || 13}`}>Read {work.chapter}:{work.verses} <span>→</span></Link></div><div><p className="eyebrow">Image information</p><p>{work.imageRights}</p><p>{work.imageUnavailable || work.imageCredit}</p><p>Image reuse: {work.imageLicense}{work.imageLicenseUrl && <> · <a href={work.imageLicenseUrl} target="_blank" rel="noreferrer">license text ↗</a></>}</p><div className="source-buttons"><a href={imageSource} target="_blank" rel="noreferrer">{work.imageFile ? "Image source" : "Available object link"}</a>{imageSource !== work.primarySource && <a href={work.primarySource} target="_blank" rel="noreferrer">{work.sourceKind || "Object record"}</a>}</div></div></section>

    <section className="related-works section-pad"><header className="section-heading"><div><p className="eyebrow">Continue looking</p><h2>Related Judiths</h2></div><p>Same moment, nearby century, or a deliberately opposed way of controlling what the viewer is allowed to see.</p></header><div className="related-grid">{related.map(w => <Link href={`/artworks/${w.slug}`} key={w.slug}><ArtworkVisual work={w} /><p>{w.dateDisplay}</p><h3>{w.title}</h3><span>{w.artist}</span></Link>)}</div></section>
    <nav className="object-next" aria-label="Adjacent artworks"><Link href={`/artworks/${previous.slug}`}><span>← Previous</span><b>{previous.artist}</b></Link><Link href={`/artworks/${next.slug}`}><span>Next →</span><b>{next.artist}</b></Link></nav>
  </main><Footer /></>;
}
