import type { Metadata } from "next";
import Link from "next/link";
import { PageShell, SectionIntro } from "../components/site-chrome";
import { artworks, artworkImage, storyEpisodes } from "../data/exhibition";

export const metadata: Metadata = { title: "The Story of Judith", description: "The Book of Judith in seven illustrated movements, with canonical history and historical context." };
const illustrations = ["cleveland-bible-initial","donatello-judith","herbert-judith","mantegna-follower-judith","rembrandt-banquet","artemisia-florence","botticelli-return-bethulia"];
export default function StoryPage() { return <PageShell className="essay-page story-page"><SectionIntro eyebrow="The book before the image" title="The Story of Judith"><p>A besieged city gives God five days. A widow refuses the deadline, crosses the enemy line, and returns with the proof that empires can bleed.</p></SectionIntro>
  <section className="canon-note"><p className="eyebrow">A book with several homes</p><h2>Scripture, deuterocanon, apocrypha—or none of these?</h2><div><p>Judith belongs to the Catholic and Orthodox biblical canons, though placement and textual form vary. Protestant traditions generally place it among the Apocrypha rather than the canonical Old Testament. It is not part of the Jewish Tanakh, and no complete Hebrew original survives.</p><p>That does not mean Jewish reception abandoned her. Medieval Hebrew retellings made Yehudit a Hanukkah heroine. Their cheese-bearing heroine is not simply copied from the Book of Judith, where Judith brings and eats her own provisions but never feeds Holofernes cheese. In several medieval accounts she is the daughter of Yohanan the High Priest and is folded into Hasmonean history rather than presented straightforwardly as Judith of Bethulia, daughter of Merari. Those later traditions connect her salty cheese with the custom of eating dairy foods during the festival. <a href="https://www.thetorah.com/article/judith-a-chanukah-heroine" target="_blank" rel="noreferrer">See Deborah Levine Gera on Judith as a Hanukkah heroine ↗</a></p><p>Those labels describe communities' canons; none is a neutral universal category. The servant who accompanies Judith is unnamed: Greek and Latin use a common noun for “maid.” “Abra” arose when the Latin <i>abra</i> was read as a personal name.</p></div></section>
  <section className="story-movements">{storyEpisodes.map(([number,title,chapter,text],i) => { const work = artworks.find(w => w.slug === illustrations[i])!; return <article key={number} id={`movement-${number}`}><div className="story-number">{number}</div><div className="story-movement-copy"><p className="eyebrow">Judith {chapter}</p><h2>{title}</h2><p>{text}</p><Link className="text-link" href={`/read?chapter=${chapter.split(/\D/)[0] || 1}`}>Read the chapter <span>→</span></Link></div><Link className="story-illustration" href={`/artworks/${work.slug}`}><img src={artworkImage(work.slug)} alt={work.alt} loading="lazy" /><span>{work.artist}, <i>{work.title}</i>, {work.dateDisplay}</span></Link></article>; })}</section>
  <section className="history-problem section-pad"><p className="eyebrow">The historical problem</p><h2>Correct details in an impossible arrangement</h2><div><p>Judith calls Nebuchadnezzar “king of the Assyrians” ruling from Nineveh, although the historical Babylonian king lived after Assyria's capital had fallen. The route of the army and the location of Bethulia resist secure reconstruction. Names and political memories from different centuries occupy the same narrative. Most scholarship places the book&apos;s composition in the late Hellenistic period, around 100 BCE, while its exact date and original language remain debated.</p><p>Rather than treating the book as failed reportage, many scholars read these collisions as purposeful features of a Jewish historical novella. The empire is every empire; its commander is the recurring arrogance of overwhelming power. That portability helps explain the story's later political life.</p><p>The artistry lies partly in reversal. Holofernes believes he is conquering through appetite and spectacle. Judith controls food, speech, dress, timing, movement, and finally his own weapon. What looks to him like surrender is strategy.</p></div></section>
  <section className="story-end"><p className="eyebrow">Continue</p><h2>The text does not settle the images.</h2><p>Now follow what artists made of the gaps, emphases, and moral tensions.</p><div><Link className="button button--primary" href="/read">Read the book</Link><Link className="button button--outline" href="/interpretation">Judith through time</Link></div></section>
  </PageShell>; }
